### ISSUE TITLE
Wrong reference for sevsegshift in SevSegShiftOne_Counter.ino

### ISSUE THREAD

**Issue by channeng** [bridystone/SevSegShift#8]
Changes required to fix example for `SevSegShiftOne_Counter.ino`.

![image](https://user-images.githubusercontent.com/10406498/121319798-253fe880-c93f-11eb-9206-42239604c4ca.png)

However, introduces inconsistency with `SevSegShift_Counter.ino`, with SevSegShift instance named as `sevseg` instead of `sevsegshift`.

**Comment by bridystone** [comment]
Argh… True!
Will fix this soon

**Comment by papat400** [comment]
Hello, thanks for your great work!
I (very) recently downloaded the sevSegShift library directly from the Arduino IDE.
The sample file SevSegShiftOne_Counter.ino is still incorrect!
It would be better if the downloaded file no longer contained this error.
Kind regards,
Thierry.
